### is how you make a commment in http file
### Get Questions

Get http://127.0.0.1:5001/api/questions
Content-Type: application/json




### Delete Quesiton

DELETE  http://127.0.0.1:5001/api/questions/6282c2fd6549f56e7dc362f3
Content-Type: application/json


### Submit Quesiton

POST  http://127.0.0.1:5001/api/questions
Content-Type: application/json

 {
   "name": "wilul",
   "content":"test",
   "link":"www"
 }
